#!/bin/sh

animelist="$HOME/.config/animecli/animelist"

get_name() {
    [ -n "$anime" ] && anime_escolhido=$(curl -s "https://goyabu.com/?s=$anime" | grep -Eo "https:\/\/goyabu.com\/assistir\/[a-zA-Z0-9-]*/" | cut -c28- | tr -d '/' | dmenu -l 30 -p 'Resultados:') || exit
    if [ -n "$anime_escolhido" ]
    then
        anime_name=$(echo "$anime_escolhido" | tr '-' ' ' | sed 's/\<./\U&/g')
        if ! grep -qi "$anime_name" "$animelist" 
        then
            echo "$anime_name" >> "$animelist"
        fi
        episodioslist=$(curl -s "https://goyabu.com/assistir/$anime_escolhido/" | grep -Eo "https:\/\/goyabu.com\/videos\/[a-zA-Z0-9-]*/" | nl) || exit
    fi
}

get_ep() {
    episodio=$(echo "$episodioslist" | awk '{print $1}' | dmenu -l 30 -p 'Episódios:') 

    [ -n "$episodio" ] && url=$(echo "$episodioslist" | sed -n "$episodio"'p' | awk '{print $2}') || exit
    [ -n "$url" ] && dunstify "animecli" "Abrindo:\n $anime_name - Episódio $episodio \nAguarde..." && mpv "$url" && get_ep || exit 
}

if [ "$1" = "-l" ]
then
    [ -f "$animelist" ] && anime=$(sort < "$animelist" | dmenu -l 30 -i -p 'Pesquisar por:' | tr ' ' '+') && get_name && get_ep
else
    anime=$(printf '' | dmenu -p 'Pesquisar por:' | tr ' ' '+') && get_name && get_ep
fi

