#!/bin/sh

usage() {
    echo "usage: ./opencli [option] [directory]"
    echo ""
    echo " -p to pdf file."
    echo " -v to video file."
    echo " -t to text file."
    echo " -h to show this menu."
}

pdfreader='zathura'
video='mpv'
editor='st vim'
files='1 - pdf\n2 - vídeo\n3 - texto'
dirlist="$HOME/.config/opencli/dirlist"

arg="$1"
[ "$arg" = "-h" ] && usage && exit

if [ "$arg" = "-g" ]
then
    [ -z "$2" ] && dir="$(sort < "$dirlist" | dmenu -l -30 -p 'Diretório:')" || dir="$2"
else
    dir="$(pwd)"
fi

if [ -n "$dir" ]
then 
    [ -z "$(grep -ix "$dir" "$dirlist")" ] && echo "$dir" >> "$dirlist"
    [ "$arg" = "-g" ] && arg="$(echo "$files" | dmenu -l 10 -p 'Abrir:' | cut -c 3,5)"

    case "$arg" in
        -p) file="$(ls "$dir" | grep -E 'pdf' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && nohup $pdfreader "$dir""/""$file" >/dev/null 2>&1 & ;;
        -v) file="$(ls "$dir" | grep -E 'mkv|mp4|avi' | dmenu -l 30 -p "Abrir:")"
            [ -n "$file" ] && nohup $video "$dir""/""$file" >/dev/null 2>&1 & ;;
        -t) file="$(ls "$dir" | grep -E 'txt|md' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && nohup $editor "$dir""/""$file" >/dev/null 2>&1 & ;;
        *) usage ;;
    esac
fi

