#!/bin/sh

usage() {
    echo "usage: ./opencli [option] [directory]"
    echo 
    echo " -p to pdf file."
    echo " -v to video file."
    echo " -t to text file."
    echo " -i to image file."
    echo " -a to audio file."
    echo " -h to show this menu."
}

pdfreader='zathura'
video='mpv'
editor='st vim'
image='sxiv'
audio='st mpv'
files='1 - pdf
2 - video
3 - text
4 - image
5 - audio'
dirlist="$HOME/.config/opencli/dirlist"

list="$(sort < "$dirlist" | uniq)"

echo "$list" > "$dirlist"

arg="$1"
[ "$arg" = "-h" ] && usage && exit

if [ "$arg" = "-g" ]
then
  [ -z "$2" ] && dir="$(dmenu -l -30 -p 'Diretório:' < "$dirlist")" || dir="$(cd "$2" && pwd)"
else
  [ -n "$2" ] && dir="$(cd "$2" && pwd)" || dir="$(pwd)"
fi

if [ -n "$dir" ]
then
    [ -z "$(grep -ix "$dir" "$dirlist")" ] && echo "$dir" >> "$dirlist"
    [ "$arg" = "-g" ] && arg="$(echo "$files" | dmenu -l 10 -i -p 'Abrir:' | cut -c 3,5)"

    case "$arg" in
        -p) file="$(ls $dir | grep -E 'pdf' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $pdfreader $dir"/""$file" ;;
        -v) file="$(ls $dir | grep -E 'mkv|mp4|avi' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $video $dir"/""$file" ;;
        -t) file="$(ls $dir | grep -E 'txt|md' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $editor $dir"/""$file" ;;
        -i) file="$(ls $dir | grep -E 'png|jpg|jpeg|gif' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $image $dir"/""$file" ;;
        -a) file="$(ls $dir | grep -E 'mp3|oga' | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $audio $dir"/""$file" ;;
        *) usage ;;
    esac
fi

