#!/bin/sh

usage() {
    echo "usage: ./opencli [option] [directory]"
    echo ""
    echo " -p to pdf file."
    echo " -v to video file."
    echo " -t to text file."
    echo " -h to show this menu."
}

pdfreader='zathura'
video='mpv'
editor='st -e vim'
files='1 - pdf\n2 - vídeo\n3 - texto'
dirlist="$HOME/.config/opencli/dirlist"

arg="$1"
[ "$arg" = "-h" ] && usage && exit

[ -z "$2" ] && dir="$(sort < "$dirlist" | dmenu -l -15 -p 'Diretório:')" || dir="$2"

if [ -n "$dir" ]
then 
    [ -z "$(grep -ix "$dir" "$dirlist")" ] && echo "$dir" >> "$dirlist"
    [ "$arg" = "-g" ] && arg="$(echo "$files" | dmenu -l 10 -p 'Abrir:' | cut -c 3,5)"

    case "$arg" in
        -p) file="$(ls "$dir"/*pdf 2>/dev/null | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && nohup $pdfreader "$file" >/dev/null 2>&1 & ;;
        -v) file="$(ls "$dir"/*mkv "$dir"/*mp4 "$dir"/*avi 2>/dev/null | dmenu -l 30 -p "Abrir:")"
            [ -n "$file" ] && nohup $video "$file" >/dev/null 2>&1 & ;;
        -t) file="$(file "$dir"/* | grep 'UTF-8 Unicode text' | cut -d':' -f1 | dmenu -l 30 -p 'Abrir:')"
            [ -n "$file" ] && $editor "$file" ;;
        *) usage ;;
    esac
fi

