#!/bin/bash

if [ "$1" == "-h" ]
then
    echo "usage: ./rmemptyspace"
    echo "Substitui espaços em branco por (_)"
else
    for arq in *' '*
    do
        if [ -f "${arq// /_}" ] 
        then
            echo "${arq// /_} já existe"
        else
            aux="${arq// /_}"
            mv -f "$arq" "aux" && mv -f "aux" "$aux"
        fi
    done
fi
