#!/bin/sh

case $1 in
	-er) xrandr --output eDP --auto --output HDMI-A-0 --auto --right-of eDP ;;
	-el) xrandr --output eDP --auto --output HDMI-A-0 --auto --left-of eDP ;;
	-po) xrandr --output eDP --auto --output HDMI-A-0 --off ;;
	-so) xrandr --output eDP --off --output HDMI-A-0 --auto ;;
	-dp) xrandr --output eDP --auto --output HDMI-A-0 --auto --same-as eDP ;;
	-dm) xrandr --output HDMI-A-0 --gamma 1.0:0.7:0.4; xrandr --output eDP --gamma 1.0:0.7:0.4 ;;
	-nm) xrandr --output HDMI-A-0 --gamma 1.0:1.0:1.0; xrandr --output eDP --gamma 1.0:1.0:1.0 ;;
esac

