#!/bin/sh

usage() {    
    echo "usage: ./screenshooter [option]"
    echo ""
    echo " -w capture full window."
    echo " -a select capture area."
    echo " -h to show this menu."
 
}

case $1 in
    -w) import -window root "$HOME/Imagens/screenshots/screen-record_$(date +"%d-%m-%Y_%H-%M-%S").png"
        dunstify "Image save in Imagens/screenshots" ;;
    -a) import "$HOME/Imagens/screenshots/screen-record_$(date +"%d-%m-%Y_%H-%M-%S").png"
        dunstify "Image save in Imagens/screenshots" ;;
     *) usage ;;
esac
