#!/bin/sh

usage() {    
    echo "usage: ./screenrecord [option]"
    echo ""
    echo " -v to record screen without audio."
    echo " -a to record screen and audio."
    echo " -h to show this menu."
}

screen()
{
    ffmpeg -video_size 1366x768 -framerate 25 -f x11grab -i :0.0+0,0 $cmd "$HOME/Vídeos/screen-record_$(date +"%d-%m-%Y_%H-%M-%S").mkv" 
    dunstify "screenrecord" "Video save in $HOME/Vídeos"
}

case $1 in
    -v) screen ;;
    -a) cmd="-f pulse -ac 2 -i default" && screen ;;
    *) usage ;;
esac
