#!/bin/sh

usage() {    
    echo "usage: ./screenshooter [option]"
    echo ""
    echo " -w capture full window."
    echo " -a select capture area."
    echo " -h to show this menu."
 
}

screen() {
    import $cmd "$HOME/Imagens/screenshots/screen-record_$(date +"%d-%m-%Y_%H-%M-%S").png"
    dunstify "screenshooter" "Image save in $HOME/Imagens/screenshots" 
}

case $1 in
    -w) cmd="-window root" && screen ;;
    -a) cmd="" && screen ;;
    *) usage ;;
esac
