#!/bin/sh

avr='#ifndef F_CPU
#define F_CPU 16000000L
#endif

#include <avr/io.h>
#include <util/delay.h>

int main() {

	while(1) {

    }

    return 0;
}'

c='#include <stdio.h>

int main() {
    
    return 0;
}'

py='def main():

if __name__ == "__main__":
    main()'

sh='#!/bin/sh'

usage() {
    echo "usage: ./templates [option] [name]"
    echo 
    echo " -avr to avr file"
    echo " -c to c file"
    echo " -py to python file"
    echo " -sh to shell file"
}

mk_file() {
    [ -n "$(find . -name "$file")" ] && echo "Arquivo já existe" && exit
    touch "$file"
}

[ -z "$1" ] && usage && exit
[ -z "$2" ] && name="main" || name="$2"

case "$1" in
    "-avr") file="$name"".c"
        mk_file
        echo "$avr" >> "$file"
        vim "$file" ;;
    "-c") file="$name"".c"
        mk_file
        echo "$c" >> "$file"
        vim "$file" ;;
     "-py") file="$name"".py"
        mk_file
        echo "$py" >> "$file"
        vim "$file" ;;  
    "-sh") file="$name"
        mk_file
        echo "$sh" >> "$file"
        chmod +x "$file"
        vim "$file" ;;
*) usage ;;
esac

