#!/bin/sh

usage() {
    echo "usage: ./tux [option]"
    echo ""
    echo " -c to calcule expression"
    echo " -d to get date"
    echo " -f to get fortune"
    echo " -w to get weather"

}

cmd="cowsay -f tux"

case $1 in
    -c) $cmd "$(echo "$2 = " && echo "scale=2; $2" | bc -l)" ;;
    -d) $cmd "$(date +'%a, %d %b %y, %H:%M')" ;;
    -f) $cmd "$(fortune)" ;;
    -w) $cmd "$(curl -Ss 'https://wttr.in/?Q&T' | cut -c16- | head -2 | xargs)" ;;
    *) usage ;;
esac

