#!/bin/sh

usage() {
    echo "usage: /.tux [option]"
    echo 
    echo " -c to calcule expression"
    echo " -d to get date"
    echo " -f to get fortune"
    echo " -s to say something"
    echo " -w to get weather"

}

responde()
{
    cowsay -f tux "$msg"
}

case $1 in
    -c) msg=$(echo "$2 = " && echo "scale=2; $2" | bc -l) && responde ;; 
    -f) msg=$(fortune) && responde ;;
    -s) msg=$2 && responde ;;
    -w) msg=$(curl -Ss 'https://wttr.in/?0&Q&T' | cut -c16- | head -2 | xargs) && responde ;;
    *) usage ;;
esac

