#!/bin/sh

ssid=$(nmcli dev wifi list | dmenu -l 30 -i -p 'Conectar:' | awk '{print $2}')

[ -n "$ssid" ] && passwd=$(printf '' | dmenu -p 'Senha?')

[ -n "$passwd" ] && status=$(nmcli dev wifi connect "$ssid" password "$passwd")

[ -n "$status" ] && dunstify "wificli" "$status"
